/* (c) Copyright Frontify Ltd., all rights reserved. */

import { defineConfig } from 'oxlint';

export default defineConfig({
    plugins: ['typescript', 'eslint', 'promise', 'unicorn', 'import'],
    jsPlugins: ['@eslint-community/eslint-plugin-eslint-comments'],
    categories: {
        correctness: 'off',
    },
    options: {
        typeAware: true,
    },
    env: {
        builtin: true,
    },
    ignorePatterns: [
        '.next',
        '*.min.*',
        '*.d.ts',
        'CHANGELOG.md',
        'dist',
        'LICENSE*',
        'output',
        'out',
        'coverage',
        'public',
        'temp',
        'package-lock.json',
        'pnpm-lock.yaml',
        'yarn.lock',
        '__snapshots__',
    ],
    rules: {
        'no-array-constructor': 'error',
        'no-unused-expressions': 'error',
        'no-unused-vars': 'error',
        'promise/always-return': 'error',
        'promise/no-return-wrap': 'error',
        'promise/param-names': 'error',
        'promise/catch-or-return': 'error',
        'promise/no-nesting': 'warn',
        'promise/no-promise-in-callback': 'warn',
        'promise/no-callback-in-promise': 'warn',
        'promise/no-new-statics': 'error',
        'promise/valid-params': 'warn',
        '@eslint-community/eslint-comments/disable-enable-pair': 'error',
        '@eslint-community/eslint-comments/no-aggregating-enable': 'error',
        '@eslint-community/eslint-comments/no-duplicate-disable': 'error',
        '@eslint-community/eslint-comments/no-unlimited-disable': 'error',
        '@eslint-community/eslint-comments/no-unused-enable': 'error',
        'typescript/await-thenable': 'error',
        'typescript/ban-ts-comment': 'error',
        'typescript/no-array-delete': 'error',
        'typescript/no-base-to-string': 'error',
        'typescript/no-duplicate-enum-values': 'error',
        'typescript/no-duplicate-type-constituents': 'error',
        'typescript/no-empty-object-type': 'error',
        'typescript/no-explicit-any': 'error',
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-floating-promises': 'error',
        'typescript/no-for-in-array': 'error',
        'typescript/no-implied-eval': 'error',
        'typescript/no-misused-new': 'error',
        'typescript/no-misused-promises': 'error',
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-redundant-type-constituents': 'error',
        'typescript/no-require-imports': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-argument': 'error',
        'typescript/no-unsafe-assignment': 'error',
        'typescript/no-unsafe-call': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-unsafe-enum-comparison': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/no-unsafe-return': 'error',
        'typescript/no-unsafe-unary-minus': 'error',
        'typescript/no-wrapper-object-types': 'error',
        'typescript/only-throw-error': 'error',
        'typescript/prefer-as-const': 'error',
        'typescript/prefer-namespace-keyword': 'error',
        'typescript/prefer-promise-reject-errors': 'error',
        'typescript/require-await': 'error',
        'typescript/restrict-plus-operands': 'error',
        'typescript/restrict-template-expressions': 'error',
        'typescript/triple-slash-reference': 'error',
        'typescript/unbound-method': 'error',
    },
    overrides: [
        {
            files: ['**/*.{js,mjs,cjs,jsx}'],
            rules: {
                'constructor-super': 'error',
                'for-direction': 'error',
                'getter-return': 'error',
                'no-async-promise-executor': 'error',
                'no-case-declarations': 'error',
                'no-class-assign': 'error',
                'no-compare-neg-zero': 'error',
                'no-cond-assign': 'error',
                'no-const-assign': 'error',
                'no-constant-binary-expression': 'error',
                'no-constant-condition': 'error',
                'no-control-regex': 'error',
                'no-debugger': 'error',
                'no-delete-var': 'error',
                'no-dupe-class-members': 'error',
                'no-dupe-else-if': 'error',
                'no-dupe-keys': 'error',
                'no-duplicate-case': 'error',
                'no-empty': 'error',
                'no-empty-character-class': 'error',
                'no-empty-pattern': 'error',
                'no-empty-static-block': 'error',
                'no-ex-assign': 'error',
                'no-extra-boolean-cast': 'error',
                'no-fallthrough': 'error',
                'no-func-assign': 'error',
                'no-global-assign': 'error',
                'no-import-assign': 'error',
                'no-invalid-regexp': 'error',
                'no-irregular-whitespace': 'error',
                'no-loss-of-precision': 'error',
                'no-misleading-character-class': 'error',
                'no-new-native-nonconstructor': 'error',
                'no-nonoctal-decimal-escape': 'error',
                'no-obj-calls': 'error',
                'no-prototype-builtins': 'error',
                'no-redeclare': 'error',
                'no-regex-spaces': 'error',
                'no-self-assign': 'error',
                'no-setter-return': 'error',
                'no-shadow-restricted-names': 'error',
                'no-sparse-arrays': 'error',
                'no-this-before-super': 'error',
                'no-unassigned-vars': 'error',
                'no-unreachable': 'error',
                'no-unsafe-finally': 'error',
                'no-unsafe-negation': 'error',
                'no-unsafe-optional-chaining': 'error',
                'no-unused-labels': 'error',
                'no-unused-private-class-members': 'error',
                'no-useless-backreference': 'error',
                'no-useless-catch': 'error',
                'no-useless-escape': 'error',
                'no-with': 'error',
                'preserve-caught-error': 'error',
                'require-yield': 'error',
                'use-isnan': 'error',
                'valid-typeof': 'error',
            },
        },
        {
            files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
            rules: {
                'constructor-super': 'off',
                'getter-return': 'off',
                'no-class-assign': 'off',
                'no-const-assign': 'off',
                'no-dupe-class-members': 'off',
                'no-dupe-keys': 'off',
                'no-func-assign': 'off',
                'no-import-assign': 'off',
                'no-new-native-nonconstructor': 'off',
                'no-obj-calls': 'off',
                'no-redeclare': 'off',
                'no-setter-return': 'off',
                'no-this-before-super': 'off',
                'no-unreachable': 'off',
                'no-unsafe-negation': 'off',
                'no-var': 'error',
                'no-with': 'off',
                'prefer-const': 'error',
                'prefer-rest-params': 'error',
                'prefer-spread': 'error',
            },
        },
        {
            files: ['**/*.json'],
            rules: {
                'no-unused-expressions': 'off',
                'no-unused-vars': 'off',
                'jsonc/comma-dangle': ['error', 'never'],
                'jsonc/no-bigint-literals': 'error',
                'jsonc/no-binary-expression': 'error',
                'jsonc/no-binary-numeric-literals': 'error',
                'jsonc/no-comments': 'error',
                'jsonc/no-dupe-keys': 'error',
                'jsonc/no-escape-sequence-in-identifier': 'error',
                'jsonc/no-floating-decimal': 'off',
                'jsonc/no-hexadecimal-numeric-literals': 'error',
                'jsonc/no-infinity': 'error',
                'jsonc/no-irregular-whitespace': 'error',
                'jsonc/no-multi-str': 'error',
                'jsonc/no-nan': 'error',
                'jsonc/no-number-props': 'error',
                'jsonc/no-numeric-separators': 'error',
                'jsonc/no-octal-numeric-literals': 'error',
                'jsonc/no-octal': 'error',
                'jsonc/no-parenthesized': 'error',
                'jsonc/no-plus-sign': 'error',
                'jsonc/no-regexp-literals': 'error',
                'jsonc/no-sparse-arrays': 'error',
                'jsonc/no-template-literals': 'error',
                'jsonc/no-undefined-value': 'error',
                'jsonc/no-unicode-codepoint-escapes': 'error',
                'jsonc/no-useless-escape': 'error',
                'jsonc/quote-props': 'off',
                'jsonc/quotes': 'off',
                'jsonc/space-unary-ops': 'off',
                'jsonc/valid-json-number': 'error',
                'jsonc/vue-custom-block/no-parsing-error': 'error',
                'jsonc/array-bracket-newline': 'off',
                'jsonc/array-bracket-spacing': ['error', 'never'],
                'jsonc/array-element-newline': 'off',
                'jsonc/comma-style': ['error', 'last'],
                'jsonc/indent': 'off',
                'jsonc/key-spacing': ['error', { beforeColon: false, afterColon: true }],
                'jsonc/object-curly-newline': ['error', { multiline: true, consistent: true }],
                'jsonc/object-curly-spacing': ['error', 'always'],
                'jsonc/object-property-newline': ['error', { allowMultiplePropertiesPerLine: true }],
                'jsonc/no-octal-escape': 'error',
                'jsonc/sort-keys': ['warn', 'asc'],
                'typescript/await-thenable': 'off',
                'typescript/no-array-delete': 'off',
                'typescript/no-base-to-string': 'off',
                'typescript/no-duplicate-type-constituents': 'off',
                'typescript/no-floating-promises': 'off',
                'typescript/no-for-in-array': 'off',
                'typescript/no-implied-eval': 'off',
                'typescript/no-misused-promises': 'off',
                'typescript/no-redundant-type-constituents': 'off',
                'typescript/no-unsafe-argument': 'off',
                'typescript/no-unsafe-assignment': 'off',
                'typescript/no-unsafe-call': 'off',
                'typescript/no-unsafe-enum-comparison': 'off',
                'typescript/no-unsafe-member-access': 'off',
                'typescript/no-unsafe-return': 'off',
                'typescript/no-unsafe-unary-minus': 'off',
                'typescript/only-throw-error': 'off',
                'typescript/prefer-promise-reject-errors': 'off',
                'typescript/require-await': 'off',
                'typescript/restrict-plus-operands': 'off',
                'typescript/restrict-template-expressions': 'off',
                'typescript/unbound-method': 'off',
            },
            jsPlugins: ['eslint-plugin-jsonc'],
        },
        {
            files: ['**/*.jsonc', '**/.vscode/**/*.json', '**/tsconfig.json', '**/tsconfig.*.json'],
            rules: {
                'no-unused-expressions': 'off',
                'no-unused-vars': 'off',
                'jsonc/no-bigint-literals': 'error',
                'jsonc/no-binary-expression': 'error',
                'jsonc/no-binary-numeric-literals': 'error',
                'jsonc/no-dupe-keys': 'error',
                'jsonc/no-escape-sequence-in-identifier': 'error',
                'jsonc/no-floating-decimal': 'off',
                'jsonc/no-hexadecimal-numeric-literals': 'error',
                'jsonc/no-infinity': 'error',
                'jsonc/no-irregular-whitespace': 'error',
                'jsonc/no-multi-str': 'error',
                'jsonc/no-nan': 'error',
                'jsonc/no-number-props': 'error',
                'jsonc/no-numeric-separators': 'error',
                'jsonc/no-octal-numeric-literals': 'error',
                'jsonc/no-octal': 'error',
                'jsonc/no-parenthesized': 'error',
                'jsonc/no-plus-sign': 'error',
                'jsonc/no-regexp-literals': 'error',
                'jsonc/no-sparse-arrays': 'error',
                'jsonc/no-template-literals': 'error',
                'jsonc/no-undefined-value': 'error',
                'jsonc/no-unicode-codepoint-escapes': 'error',
                'jsonc/no-useless-escape': 'error',
                'jsonc/quote-props': 'off',
                'jsonc/quotes': 'off',
                'jsonc/space-unary-ops': 'off',
                'jsonc/valid-json-number': 'error',
                'jsonc/vue-custom-block/no-parsing-error': 'error',
                'jsonc/array-bracket-newline': 'off',
                'jsonc/array-bracket-spacing': 'off',
                'jsonc/array-element-newline': 'off',
                'jsonc/comma-dangle': 'off',
                'jsonc/comma-style': 'off',
                'jsonc/indent': 'off',
                'jsonc/key-spacing': 'off',
                'jsonc/object-curly-newline': 'off',
                'jsonc/object-curly-spacing': 'off',
                'jsonc/object-property-newline': 'off',
                'typescript/await-thenable': 'off',
                'typescript/no-array-delete': 'off',
                'typescript/no-base-to-string': 'off',
                'typescript/no-duplicate-type-constituents': 'off',
                'typescript/no-floating-promises': 'off',
                'typescript/no-for-in-array': 'off',
                'typescript/no-implied-eval': 'off',
                'typescript/no-misused-promises': 'off',
                'typescript/no-redundant-type-constituents': 'off',
                'typescript/no-unsafe-argument': 'off',
                'typescript/no-unsafe-assignment': 'off',
                'typescript/no-unsafe-call': 'off',
                'typescript/no-unsafe-enum-comparison': 'off',
                'typescript/no-unsafe-member-access': 'off',
                'typescript/no-unsafe-return': 'off',
                'typescript/no-unsafe-unary-minus': 'off',
                'typescript/only-throw-error': 'off',
                'typescript/prefer-promise-reject-errors': 'off',
                'typescript/require-await': 'off',
                'typescript/restrict-plus-operands': 'off',
                'typescript/restrict-template-expressions': 'off',
                'typescript/unbound-method': 'off',
            },
            jsPlugins: ['eslint-plugin-jsonc'],
        },
        {
            files: ['**/*.json5'],
            rules: {
                'no-unused-expressions': 'off',
                'no-unused-vars': 'off',
                'jsonc/no-bigint-literals': 'error',
                'jsonc/no-binary-expression': 'error',
                'jsonc/no-binary-numeric-literals': 'error',
                'jsonc/no-dupe-keys': 'error',
                'jsonc/no-escape-sequence-in-identifier': 'error',
                'jsonc/no-irregular-whitespace': 'error',
                'jsonc/no-number-props': 'error',
                'jsonc/no-numeric-separators': 'error',
                'jsonc/no-octal-numeric-literals': 'error',
                'jsonc/no-octal': 'error',
                'jsonc/no-parenthesized': 'error',
                'jsonc/no-regexp-literals': 'error',
                'jsonc/no-sparse-arrays': 'error',
                'jsonc/no-template-literals': 'error',
                'jsonc/no-undefined-value': 'error',
                'jsonc/no-unicode-codepoint-escapes': 'error',
                'jsonc/no-useless-escape': 'error',
                'jsonc/space-unary-ops': 'off',
                'jsonc/vue-custom-block/no-parsing-error': 'error',
                'jsonc/array-bracket-newline': 'off',
                'jsonc/array-bracket-spacing': 'off',
                'jsonc/array-element-newline': 'off',
                'jsonc/comma-dangle': 'off',
                'jsonc/comma-style': 'off',
                'jsonc/indent': 'off',
                'jsonc/key-spacing': 'off',
                'jsonc/no-floating-decimal': 'off',
                'jsonc/object-curly-newline': 'off',
                'jsonc/object-curly-spacing': 'off',
                'jsonc/object-property-newline': 'off',
                'jsonc/quote-props': 'off',
                'jsonc/quotes': 'off',
                'typescript/await-thenable': 'off',
                'typescript/no-array-delete': 'off',
                'typescript/no-base-to-string': 'off',
                'typescript/no-duplicate-type-constituents': 'off',
                'typescript/no-floating-promises': 'off',
                'typescript/no-for-in-array': 'off',
                'typescript/no-implied-eval': 'off',
                'typescript/no-misused-promises': 'off',
                'typescript/no-redundant-type-constituents': 'off',
                'typescript/no-unsafe-argument': 'off',
                'typescript/no-unsafe-assignment': 'off',
                'typescript/no-unsafe-call': 'off',
                'typescript/no-unsafe-enum-comparison': 'off',
                'typescript/no-unsafe-member-access': 'off',
                'typescript/no-unsafe-return': 'off',
                'typescript/no-unsafe-unary-minus': 'off',
                'typescript/only-throw-error': 'off',
                'typescript/prefer-promise-reject-errors': 'off',
                'typescript/require-await': 'off',
                'typescript/restrict-plus-operands': 'off',
                'typescript/restrict-template-expressions': 'off',
                'typescript/unbound-method': 'off',
            },
            jsPlugins: ['eslint-plugin-jsonc'],
        },
        {
            files: ['**/*.yaml', '**/*.yml'],
            rules: {
                'no-irregular-whitespace': 'off',
                'no-unused-vars': 'off',
                'yml/no-empty-document': 'off',
                'yml/no-empty-key': 'error',
                'yml/no-empty-mapping-value': 'off',
                'yml/no-empty-sequence-entry': 'error',
                'yml/no-irregular-whitespace': 'error',
                'yml/no-tab-indent': 'error',
                'yml/vue-custom-block/no-parsing-error': 'error',
                'yml/block-mapping-colon-indicator-newline': 'off',
                'yml/block-mapping-question-indicator-newline': 'off',
                'yml/block-sequence-hyphen-indicator-newline': 'off',
                'yml/flow-mapping-curly-newline': 'off',
                'yml/flow-mapping-curly-spacing': 'off',
                'yml/flow-sequence-bracket-newline': 'off',
                'yml/flow-sequence-bracket-spacing': 'off',
                'yml/indent': ['error', 4, { indicatorValueIndent: 2 }],
                'yml/key-spacing': 'off',
                'yml/no-multiple-empty-lines': 'off',
                'yml/no-trailing-zeros': 'off',
                'yml/quotes': ['error', { prefer: 'single', avoidEscape: false }],
                'typescript/await-thenable': 'off',
                'typescript/no-array-delete': 'off',
                'typescript/no-base-to-string': 'off',
                'typescript/no-duplicate-type-constituents': 'off',
                'typescript/no-floating-promises': 'off',
                'typescript/no-for-in-array': 'off',
                'typescript/no-implied-eval': 'off',
                'typescript/no-misused-promises': 'off',
                'typescript/no-redundant-type-constituents': 'off',
                'typescript/no-unsafe-argument': 'off',
                'typescript/no-unsafe-assignment': 'off',
                'typescript/no-unsafe-call': 'off',
                'typescript/no-unsafe-enum-comparison': 'off',
                'typescript/no-unsafe-member-access': 'off',
                'typescript/no-unsafe-return': 'off',
                'typescript/no-unsafe-unary-minus': 'off',
                'typescript/only-throw-error': 'off',
                'typescript/prefer-promise-reject-errors': 'off',
                'typescript/require-await': 'off',
                'typescript/restrict-plus-operands': 'off',
                'typescript/restrict-template-expressions': 'off',
                'typescript/unbound-method': 'off',
                '@stylistic/spaced-comment': 'off',
            },
            jsPlugins: ['eslint-plugin-yml', '@stylistic/eslint-plugin'],
        },
        {
            files: ['**/*.{js,mjs,cjs,jsx,ts,tsx,mts,cts}'],
            plugins: ['import'],
            jsPlugins: ['@stylistic/eslint-plugin'],
            env: {
                es2026: true,
                browser: true,
                node: true,
            },
            rules: {
                'prefer-template': 'error',
                'no-var': 'error',
                eqeqeq: 'error',
                'no-eval': 'error',
                'no-extra-bind': 'error',
                'vars-on-top': 'error',
                'block-scoped-var': 'error',
                'array-callback-return': 'error',
                'no-use-before-define': 'off',
                'object-shorthand': ['error', 'always', { ignoreConstructors: false, avoidQuotes: true }],
                'no-case-declarations': 'error',
                'no-multi-str': 'error',
                'no-void': 'error',
                'no-return-assign': 'off',
                'prefer-exponentiation-operator': 'error',
                'prefer-rest-params': 'error',
                'prefer-spread': 'error',
                'no-debugger': 'error',
                'no-constant-condition': 'warn',
                'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
                'no-unreachable': 'error',
                'no-unused-labels': 'error',
                'no-useless-computed-key': 'error',
                'no-useless-concat': 'error',
                'no-useless-escape': 'error',
                'no-useless-rename': [
                    'error',
                    { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false },
                ],
                'no-with': 'error',
                '@stylistic/spaced-comment': [
                    'error',
                    'always',
                    {
                        line: { markers: ['/'], exceptions: ['/', '#'] },
                        block: { markers: ['!'], exceptions: ['*'], balanced: true },
                    },
                ],
                'unicorn/error-message': 'error',
                'unicorn/escape-case': 'error',
                'unicorn/no-instanceof-array': 'error',
                'unicorn/no-new-buffer': 'error',
                'unicorn/prefer-array-find': 'error',
                'unicorn/prefer-default-parameters': 'error',
                'unicorn/prefer-includes': 'error',
                'unicorn/prefer-string-starts-ends-with': 'error',
                'unicorn/prefer-string-replace-all': 'error',
                'unicorn/prefer-dom-node-text-content': 'error',
                'unicorn/prefer-type-error': 'error',
                'unicorn/throw-new-error': 'error',
                'unicorn/prefer-node-protocol': 'error',
                'unicorn/no-array-for-each': 'error',
                'unicorn/custom-error-definition': 'error',
                'unicorn/explicit-length-check': 'error',
                'unicorn/no-await-expression-member': 'error',
                'unicorn/no-new-array': 'error',
                'unicorn/no-this-assignment': 'error',
                'unicorn/no-useless-length-check': 'error',
                'unicorn/catch-error-name': 'error',
                'import/no-relative-parent-imports': 'off',
                'import/no-named-as-default': 'off',
                'import/exports-last': 'off',
                'import/no-namespace': 'off',
                'import/extensions': 'off',
                'import/namespace': 'off',
                'import/default': 'off',
                'import/prefer-default-export': 'off',
                'import/max-dependencies': 'off',
                'import/no-unassigned-import': 'off',
                'import/no-default-export': 'off',
                'import/no-named-export': 'off',
                'import/group-exports': 'off',
                'import/no-duplicates': ['error', { 'prefer-inline': true }],
                'import/consistent-type-specifier-style': ['error', 'prefer-inline'],
            },
        },
        {
            files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
            rules: {
                'no-unused-vars': [
                    'error',
                    { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
                ],
                'no-dupe-class-members': 'error',
                'typescript/no-explicit-any': 'warn',
                'typescript/no-implied-eval': 'error',
                'typescript/dot-notation': ['error', { allowKeywords: true }],
                'typescript/await-thenable': 'error',
                'typescript/no-for-in-array': 'error',
                'typescript/no-unnecessary-type-assertion': 'error',
                'typescript/no-unsafe-argument': 'error',
                'typescript/no-unsafe-call': 'error',
                'typescript/no-unsafe-return': 'error',
                'typescript/require-await': 'error',
                'typescript/restrict-plus-operands': 'error',
                'typescript/restrict-template-expressions': 'error',
                'typescript/unbound-method': 'off',
                'typescript/consistent-type-imports': [
                    'error',
                    { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
                ],
                'typescript/no-misused-promises': [
                    'error',
                    { checksVoidReturn: { attributes: false } },
                ],
            },
        },
        {
            files: ['**/package.json'],
            rules: {
                'typescript/await-thenable': 'off',
                'typescript/no-array-delete': 'off',
                'typescript/no-base-to-string': 'off',
                'typescript/no-duplicate-type-constituents': 'off',
                'typescript/no-floating-promises': 'off',
                'typescript/no-for-in-array': 'off',
                'typescript/no-implied-eval': 'off',
                'typescript/no-misused-promises': 'off',
                'typescript/no-redundant-type-constituents': 'off',
                'typescript/no-unsafe-argument': 'off',
                'typescript/no-unsafe-assignment': 'off',
                'typescript/no-unsafe-call': 'off',
                'typescript/no-unsafe-enum-comparison': 'off',
                'typescript/no-unsafe-member-access': 'off',
                'typescript/no-unsafe-return': 'off',
                'typescript/no-unsafe-unary-minus': 'off',
                'typescript/only-throw-error': 'off',
                'typescript/prefer-promise-reject-errors': 'off',
                'typescript/require-await': 'off',
                'typescript/restrict-plus-operands': 'off',
                'typescript/restrict-template-expressions': 'off',
                'typescript/unbound-method': 'off',
                'jsonc/sort-keys': [
                    'error',
                    {
                        pathPattern: '^$',
                        order: [
                            'publisher',
                            'name',
                            'displayName',
                            'type',
                            'version',
                            'private',
                            'packageManager',
                            'description',
                            'author',
                            'license',
                            'funding',
                            'homepage',
                            'repository',
                            'bugs',
                            'keywords',
                            'categories',
                            'sideEffects',
                            'exports',
                            'main',
                            'module',
                            'unpkg',
                            'jsdelivr',
                            'types',
                            'typesVersions',
                            'bin',
                            'icon',
                            'files',
                            'engines',
                            'activationEvents',
                            'contributes',
                            'scripts',
                            'peerDependencies',
                            'peerDependenciesMeta',
                            'dependencies',
                            'optionalDependencies',
                            'devDependencies',
                            'pnpm',
                            'overrides',
                            'resolutions',
                            'eslintConfig',
                        ],
                    },
                    {
                        pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies$',
                        order: { type: 'asc' },
                    },
                    {
                        pathPattern: '^exports.*$',
                        order: ['types', 'require', 'import'],
                    },
                ],
            },
            jsPlugins: ['eslint-plugin-jsonc'],
        },
        {
            files: ['**/*.d.ts'],
            plugins: ['import'],
            rules: {
                'import/no-duplicates': 'off',
            },
        },
        {
            files: ['scripts/**/*', 'cli/**/*'],
            rules: {
                'no-console': 'off',
            },
        },
        {
            files: [
                '**/*.test.ts',
                '**/*.test.tsx',
                '**/*.test.js',
                '**/*.test.jsx',
                '**/*.spec.ts',
                '**/*.spec.tsx',
                '**/*.spec.js',
                '**/*.spec.jsx',
                '**/*.spec.cy.ts',
                '**/*.spec.cy.tsx',
                '**/*.spec.cy.js',
                '**/*.spec.cy.jsx',
                '**/*.spec.ct.ts',
                '**/*.spec.ct.tsx',
                '**/*.spec.ct.js',
                '**/*.spec.ct.jsx',
            ],
            rules: {
                'no-unused-expressions': 'off',
                'no-only-tests/no-only-tests': 'error',
                'typescript/unbound-method': 'off',
            },
            jsPlugins: ['eslint-plugin-no-only-tests'],
        },
        {
            files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
            rules: {
                curly: ['error', 'all'],
            },
        },
        // TODO: enable when oxlint supports @eslint/markdown as a jsPlugin
        // {
        //     files: ['**/*.md'],
        //     jsPlugins: ['@eslint/markdown'],
        //     rules: {
        //         'markdown/fenced-code-language': 'error',
        //         'markdown/heading-increment': 'error',
        //         'markdown/no-duplicate-definitions': 'error',
        //         'markdown/no-empty-definitions': 'error',
        //         'markdown/no-empty-images': 'error',
        //         'markdown/no-empty-links': 'error',
        //         'markdown/no-invalid-label-refs': 'error',
        //         'markdown/no-missing-atx-heading-space': 'error',
        //         'markdown/no-missing-label-refs': 'error',
        //         'markdown/no-missing-link-fragments': 'error',
        //         'markdown/no-multiple-h1': 'error',
        //         'markdown/no-reference-like-urls': 'error',
        //         'markdown/no-reversed-media-syntax': 'error',
        //         'markdown/no-space-in-emphasis': 'error',
        //         'markdown/no-unused-definitions': 'error',
        //         'markdown/require-alt-text': 'error',
        //         'markdown/table-column-count': 'error',
        //     },
        // },
    ],
});
