/* (c) Copyright Frontify Ltd., all rights reserved. */

import basicConfig from '@frontify/oxlint-config-basic';
import { defineConfig } from 'oxlint';

export default defineConfig({
    extends: [basicConfig],
    plugins: ['typescript', 'eslint', 'promise', 'unicorn', 'import', 'jsx-a11y'],
    jsPlugins: [
        '@eslint-community/eslint-plugin-eslint-comments',
        '@eslint-react/eslint-plugin',
    ],
    settings: {
        'react-x': {
            version: 'detect',
            importSource: 'react',
            polymorphicPropName: 'as',
        },
    },
    rules: {
        '@eslint-react/error-boundaries': 'error',
        '@eslint-react/exhaustive-deps': 'warn',
        '@eslint-react/no-access-state-in-setstate': 'error',
        '@eslint-react/no-array-index-key': 'warn',
        '@eslint-react/no-children-count': 'warn',
        '@eslint-react/no-children-for-each': 'warn',
        '@eslint-react/no-children-map': 'warn',
        '@eslint-react/no-children-only': 'warn',
        '@eslint-react/no-children-to-array': 'warn',
        '@eslint-react/no-clone-element': 'warn',
        '@eslint-react/no-component-will-mount': 'error',
        '@eslint-react/no-component-will-receive-props': 'error',
        '@eslint-react/no-component-will-update': 'error',
        '@eslint-react/no-context-provider': 'warn',
        '@eslint-react/no-create-ref': 'error',
        '@eslint-react/no-direct-mutation-state': 'error',
        '@eslint-react/no-forward-ref': 'warn',
        '@eslint-react/no-missing-key': 'error',
        '@eslint-react/no-nested-component-definitions': 'error',
        '@eslint-react/no-nested-lazy-component-declarations': 'error',
        '@eslint-react/no-set-state-in-component-did-mount': 'warn',
        '@eslint-react/no-set-state-in-component-did-update': 'warn',
        '@eslint-react/no-set-state-in-component-will-update': 'warn',
        '@eslint-react/no-unnecessary-use-prefix': 'warn',
        '@eslint-react/no-unsafe-component-will-mount': 'warn',
        '@eslint-react/no-unsafe-component-will-receive-props': 'warn',
        '@eslint-react/no-unsafe-component-will-update': 'warn',
        '@eslint-react/no-unused-class-component-members': 'warn',
        '@eslint-react/no-unused-state': 'warn',
        '@eslint-react/no-use-context': 'warn',
        '@eslint-react/purity': 'warn',
        '@eslint-react/rules-of-hooks': 'error',
        '@eslint-react/set-state-in-effect': 'warn',
        '@eslint-react/set-state-in-render': 'error',
        '@eslint-react/static-components': 'error',
        '@eslint-react/unsupported-syntax': 'error',
        '@eslint-react/use-memo': 'error',
        '@eslint-react/use-state': 'warn',
        '@eslint-react/jsx-no-children-prop': 'warn',
        '@eslint-react/jsx-no-children-prop-with-children': 'error',
        '@eslint-react/jsx-no-comment-textnodes': 'warn',
        '@eslint-react/jsx-no-key-after-spread': 'error',
        '@eslint-react/jsx-no-leaked-dollar': 'warn',
        '@eslint-react/jsx-no-leaked-semicolon': 'warn',
        '@eslint-react/jsx-no-namespace': 'error',
        '@eslint-react/rsc-function-definition': 'error',
        '@eslint-react/dom-no-dangerously-set-innerhtml': 'warn',
        '@eslint-react/dom-no-dangerously-set-innerhtml-with-children': 'error',
        '@eslint-react/dom-no-find-dom-node': 'error',
        '@eslint-react/dom-no-flush-sync': 'error',
        '@eslint-react/dom-no-hydrate': 'error',
        '@eslint-react/dom-no-render': 'error',
        '@eslint-react/dom-no-render-return-value': 'error',
        '@eslint-react/dom-no-script-url': 'warn',
        '@eslint-react/dom-no-unsafe-iframe-sandbox': 'warn',
        '@eslint-react/dom-no-use-form-state': 'error',
        '@eslint-react/dom-no-void-elements-with-children': 'error',
        '@eslint-react/web-api-no-leaked-event-listener': 'warn',
        '@eslint-react/web-api-no-leaked-fetch': 'warn',
        '@eslint-react/web-api-no-leaked-interval': 'warn',
        '@eslint-react/web-api-no-leaked-resize-observer': 'warn',
        '@eslint-react/web-api-no-leaked-timeout': 'warn',
        '@eslint-react/naming-convention-context-name': 'warn',
        '@eslint-react/naming-convention-id-name': 'warn',
        '@eslint-react/naming-convention-ref-name': 'warn',
        'jsx-a11y/alt-text': 'error',
        'jsx-a11y/anchor-has-content': 'error',
        'jsx-a11y/anchor-is-valid': 'error',
        'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
        'jsx-a11y/aria-props': 'error',
        'jsx-a11y/aria-proptypes': 'error',
        'jsx-a11y/aria-role': 'error',
        'jsx-a11y/aria-unsupported-elements': 'error',
        'jsx-a11y/autocomplete-valid': 'error',
        'jsx-a11y/click-events-have-key-events': 'error',
        'jsx-a11y/heading-has-content': 'error',
        'jsx-a11y/html-has-lang': 'error',
        'jsx-a11y/iframe-has-title': 'error',
        'jsx-a11y/img-redundant-alt': 'error',
        'jsx-a11y/interactive-supports-focus': [
            'error',
            { tabbable: ['button', 'checkbox', 'link', 'searchbox', 'spinbutton', 'switch', 'textbox'] },
        ],
        'jsx-a11y/label-has-associated-control': 'error',
        'jsx-a11y/media-has-caption': 'error',
        'jsx-a11y/mouse-events-have-key-events': 'error',
        'jsx-a11y/no-access-key': 'error',
        'jsx-a11y/no-autofocus': 'error',
        'jsx-a11y/no-distracting-elements': 'error',
        'jsx-a11y/no-interactive-element-to-noninteractive-role': [
            'error',
            { tr: ['none', 'presentation'], canvas: ['img'] },
        ],
        'jsx-a11y/no-noninteractive-element-interactions': [
            'error',
            {
                handlers: ['onClick', 'onError', 'onLoad', 'onMouseDown', 'onMouseUp', 'onKeyPress', 'onKeyDown', 'onKeyUp'],
                alert: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
                body: ['onError', 'onLoad'],
                dialog: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
                iframe: ['onError', 'onLoad'],
                img: ['onError', 'onLoad'],
            },
        ],
        'jsx-a11y/no-noninteractive-element-to-interactive-role': [
            'error',
            {
                ul: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
                ol: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
                li: ['menuitem', 'menuitemradio', 'menuitemcheckbox', 'option', 'row', 'tab', 'treeitem'],
                table: ['grid'],
                td: ['gridcell'],
                fieldset: ['radiogroup', 'presentation'],
            },
        ],
        'jsx-a11y/no-noninteractive-tabindex': [
            'error',
            { tags: [], roles: ['tabpanel'], allowExpressionValues: true },
        ],
        // TODO: fix me - rule has a bug with <input role="checkbox"> (https://github.com/oxc-project/oxc/issues/22743)
        'jsx-a11y/no-redundant-roles': 'off',
        'jsx-a11y/no-static-element-interactions': [
            'error',
            {
                allowExpressionValues: true,
                handlers: ['onClick', 'onMouseDown', 'onMouseUp', 'onKeyPress', 'onKeyDown', 'onKeyUp'],
            },
        ],
        'jsx-a11y/role-has-required-aria-props': 'error',
        'jsx-a11y/role-supports-aria-props': 'error',
        'jsx-a11y/scope': 'error',
        'jsx-a11y/tabindex-no-positive': 'error',
    },
    overrides: [
        // TODO: fix me when the kit plugin can be loaded in oxlint
        // {
        //     files: ['**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts}'],
        //     jsPlugins: ['@eslint-react/kit'],
        //     rules: {
        //         '@eslint-react/kit/jsx-shorthand-boolean': 'error',
        //     },
        // },
        {
            files: ['**/*.{js,jsx,ts,tsx}'],
            jsPlugins: ['@eslint-react/eslint-plugin'],
            rules: {
                '@eslint-react/exhaustive-deps': 'error',
                '@eslint-react/no-children-for-each': 'off',
                '@eslint-react/no-children-count': 'off',
                '@eslint-react/no-children-map': 'off',
                '@eslint-react/no-children-to-array': 'off',
                '@eslint-react/no-class-component': 'error',
                '@eslint-react/no-duplicate-key': 'error',
                // TODO: fix me when the plugin supports type-aware linting with oxlint (currently has dep on `@typescript-eslint/*`)
                // '@eslint-react/no-implicit-key': 'error',
                '@eslint-react/no-missing-component-display-name': 'warn',
                '@eslint-react/no-missing-context-display-name': 'error',
                '@eslint-react/no-unstable-context-value': 'error',
                '@eslint-react/jsx-no-useless-fragment': 'error',
                // TODO: fix me when the plugin supports type-aware linting with oxlint (currently has dep on `@typescript-eslint/*`)
                // '@eslint-react/no-unused-props': 'error',
                '@eslint-react/no-unnecessary-use-prefix': 'error',
                '@eslint-react/dom-no-missing-button-type': 'error',
                '@eslint-react/dom-no-missing-iframe-sandbox': 'error',
                '@eslint-react/naming-convention-context-name': 'error',
                '@eslint-react/use-state': 'error',
            },
        },
        {
            files: [
                '**/*.test.ts',
                '**/*.test.tsx',
                '**/*.test.js',
                '**/*.test.jsx',
                '**/*.spec.ts',
                '**/*.spec.tsx',
                '**/*.spec.js',
                '**/*.spec.jsx',
                '**/*.spec.cy.ts',
                '**/*.spec.cy.tsx',
                '**/*.spec.cy.js',
                '**/*.spec.cy.jsx',
                '**/*.spec.ct.ts',
                '**/*.spec.ct.tsx',
                '**/*.spec.ct.js',
                '**/*.spec.ct.jsx',
            ],
            jsPlugins: ['@eslint-react/eslint-plugin'],
            rules: {
                '@eslint-react/no-unnecessary-use-prefix': 'off',
                '@eslint-react/no-missing-context-display-name': 'off',
                '@eslint-react/no-create-ref': 'off',
                '@eslint-react/no-unstable-context-value': 'off',
                'jsx-a11y/no-static-element-interactions': 'off',
                'jsx-a11y/click-events-have-key-events': 'off',
            },
        },
        {
            files: ['**/*.json', '**/*.yaml', '**/*.yml'],
            jsPlugins: ['@eslint-react/eslint-plugin'],
            rules: {
                '@eslint-react/no-implicit-children': 'off',
                '@eslint-react/no-implicit-key': 'off',
                '@eslint-react/no-implicit-ref': 'off',
                '@eslint-react/no-leaked-conditional-rendering': 'off',
                '@eslint-react/no-unused-props': 'off',
            },
        },
    ],
});
