name: Semantic Pull Request Title

on:
    pull_request:
        types:
            - opened
            - edited
            - reopened
            - synchronize

jobs:
    semantic-pr-title:
        runs-on: self-hosted-ubuntu-22.04-arm-2-cores
        timeout-minutes: 10

        steps:
            - name: Check PR title
              uses: amannn/action-semantic-pull-request@v6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
